version: '3.3'

services:
    maria_db:
        image: mariadb:latest # 
        volumes:
          - ./data_db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: themerealise # 
            MYSQL_DATABASE: proj_plugin_theme # 
            MYSQL_USER: CF # 
            MYSQL_PASSWORD: digital2022 # 

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.9 # 
        links:
          - maria_db # 
        environment:
          VIRTUAL_HOST: projetwp.real
          PMA_HOST: maria_db
          PMA_PORT: 3306
        ports:
          - '8000:80' # 

    wordpress:
        image: wordpress:latest # 
        depends_on:
            - maria_db # 
        ports:
            - 8800:80 # 
        environment:
            VIRTUAL_HOST: projetwp.real
            WORDPRESS_DB_HOST: maria_db:3306
            WORDPRESS_DB_USER: CF # 
            WORDPRESS_DB_PASSWORD: digital2022 # 
            WORDPRESS_DB_NAME: proj_plugin_theme # 
            WORDPRESS_TABLE_PREFIX: ppth_db_ # 
        working_dir: /var/www/html # 
        volumes:
          - .:/var/www/html/ # 
        sysctls:
         # 
          - net.ipv4.ip_unprivileged_port_start=0
        user: "${UID:-1001}:${UID:-1001}"
    #      
    ftp:
      image: stilliard/pure-ftpd:latest
      #
      ports:
        - "18004:21"
        - "30000-30009:30000-30009"
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      environment:
        PUBLICHOST: localhost #
        FTP_USER_NAME: "CF" #
        FTP_USER_PASS: "digital2022" #
        FTP_USER_HOME: "/var/www/html"
        FTP_USER_UID: 33 #
        FTP_USER_GID: 33 #
      volumes:
        - .:/var/www/html
 
volumes:
    data_db:
